import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import vm from 'node:vm';
const root=process.cwd(), engine=readFileSync(join(root,'assets/js/calculators/engine.js'),'utf8');
const injected=engine.replace('const id = document.body.dataset.calc;', 'globalThis.__configs=configs; const id = document.body.dataset.calc;');
const sandbox={Math,Number,Intl,setTimeout:()=>{},window:{},document:{body:{dataset:{calc:'__none__'}},querySelector:()=>null}}; vm.runInNewContext(injected,sandbox); const configs=sandbox.__configs, errors=[];
const pages=readdirSync(join(root,'tools')).filter(file=>file.endsWith('-calculator.html')).map(file=>join(root,'tools',file)); const calcIds=pages.map(file=>(readFileSync(file,'utf8').match(/<body data-calc="([^"]+)"/)||[])[1]);
const expected={mtbf:100,mttr:4,mttf:200,failureRate:.002,reliability:Math.exp(-.1),series:.98*.96*.99,parallel:1-(.1*.2*.3),availability:400/408,oee:(7/8)*((.5*800/60)/7)*(760/800),backlog:3.75,downtimeCost:22500,repairReplace:33000,roi:.44,reorderPoint:81,safetyStock:1.65*4*Math.sqrt(21),weibullReliability:Math.exp(-.25),b10Life:1000*Math.sqrt(-Math.log(.9)),hazardRate:.001,expectedFailures:10,kOutOfN:.99144,operationalAvailability:400/420,reliabilityToMtbf:-100/Math.log(.9),lostProduction:640,maintenanceCostPerAsset:2000,maintenanceCostRav:.06,lifecycleMaintenanceCost:60000*((Math.pow(1.03,10)-1)/.03),leadTimeDemand:63,eoq:Math.sqrt(15000),inventoryTurnover:4};
const rejectsInvalid=value=>Number.isFinite(value)&&value>=0;
if(!engine.includes('Number.isFinite(value) && value >= 0')||[NaN,Infinity,-Infinity,-1].some(rejectsInvalid)) errors.push('engine does not enforce NaN, Infinity, or negative input validation'); if(!engine.includes('type="number" min="0"')||!engine.includes('required')) errors.push('calculator inputs do not enforce numeric, non-negative, required browser validation'); if(!engine.includes("form.addEventListener('reset'")) errors.push('engine reset handler missing');
for(const id of calcIds){const cfg=configs[id];if(!cfg){errors.push(`${id}: page has no engine config`);continue;} const values=Object.fromEntries(cfg.fields.map(([key,, ,sample])=>[key,Number(sample)])); if(!cfg.fields.every(([,label,unit])=>label&&unit))errors.push(`${id}: missing input label or unit`); const normal=cfg.calc(values);if(!normal||!Number.isFinite(normal.value)||!normal.text)errors.push(`${id}: normal sample result invalid`);if(Math.abs(normal.value-expected[id])>1e-9)errors.push(`${id}: formula result differs from expected (${normal.value} vs ${expected[id]})`); const zero=Object.fromEntries(cfg.fields.map(([key])=>[key,0])); if(!cfg.valid||cfg.valid(zero)){const result=cfg.calc(zero);if(result&&(!Number.isFinite(result.value)||Number.isNaN(result.value)))errors.push(`${id}: zero input creates invalid result`);} const extreme=Object.fromEntries(cfg.fields.map(([key])=>[key,1e100])); if(!cfg.valid||cfg.valid(extreme)){const result=cfg.calc(extreme);if(result&&(!Number.isFinite(result.value)||Number.isNaN(result.value)))errors.push(`${id}: extreme input creates invalid result`);} const html=readFileSync(pages[calcIds.indexOf(id)],'utf8'); for(const heading of ['What this calculator does','When to use it','Inputs and formula','Worked example and interpretation','Practical notes and limitations'])if(!html.includes(heading))errors.push(`${id}: thin-content section missing (${heading})`); if(!/class="related"/.test(html))errors.push(`${id}: related internal links missing`);}
if(new Set(calcIds).size!==29||calcIds.length!==29) errors.push(`expected 29 calculator pages; found ${calcIds.length}`); if(Object.keys(configs).length!==29) errors.push(`expected 29 calculator configs; found ${Object.keys(configs).length}`);
console.log(`Calculator QA tested ${calcIds.length} calculators: normal samples, zero, extreme values, required units, reset handler, content sections, and formula outputs.`);if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log('PASS: calculator engine initialization, validation guards, formulas, results, units, reset, and content coverage.');
