import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
const root = process.cwd();
const walk = d => readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()&&!['.git','partials','assets'].includes(e.name)?walk(join(d,e.name)):e.isFile()&&e.name.endsWith('.html')?[join(d,e.name)]:[]);
const files=walk(root).filter(f=>!f.endsWith('404.html')); let errors=[]; const titles=new Map(),descs=new Map(); const publicUrls=[];
const urlFor=f=>{let r=relative(root,f).replaceAll('\\','/');return r==='index.html'?'https://reliabilitybench.com/':r.endsWith('/index.html')?`https://reliabilitybench.com/${r.slice(0,-10)}`:`https://reliabilitybench.com/${r}`};
for(const f of files){const h=readFileSync(f,'utf8'); const rel=relative(root,f); const title=(h.match(/<title>([^<]+)<\/title>/i)||[])[1]; const desc=(h.match(/<meta name="description" content="([^"]+)"/i)||[])[1]; const canonical=(h.match(/<link rel="canonical" href="([^"]+)"/i)||[])[1]; if(!/^<!doctype html>/i.test(h)||!/<html[\s>]/i.test(h)||!/<\/html>\s*$/i.test(h)||!/<head[\s>]/i.test(h)||!/<\/head>/i.test(h)||!/<body[\s>]/i.test(h)||!/<\/body>/i.test(h))errors.push(`${rel}: malformed HTML document structure`); if((h.match(/<a\b/gi)||[]).length!==(h.match(/<\/a>/gi)||[]).length)errors.push(`${rel}: unclosed or mis-nested anchor`); if(!title||!desc||!canonical)errors.push(`${rel}: missing title, description, or canonical`); if(canonical!==urlFor(f))errors.push(`${rel}: canonical mismatch ${canonical}`); if(!h.includes('G-6Z73P5MMNS'))errors.push(`${rel}: GA4 missing`); if((h.match(/googletagmanager\.com\/gtag\/js\?id=G-6Z73P5MMNS/g)||[]).length!==1||(h.match(/gtag\('config','G-6Z73P5MMNS'\)/g)||[]).length!==1)errors.push(`${rel}: GA4 duplicated or malformed`); if(title){if(titles.has(title))errors.push(`${rel}: duplicate title with ${titles.get(title)}`);titles.set(title,rel)} if(desc){if(descs.has(desc))errors.push(`${rel}: duplicate description with ${descs.get(desc)}`);descs.set(desc,rel)} const ids=[...h.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]); if(new Set(ids).size!==ids.length)errors.push(`${rel}: duplicate IDs`); const text=h.replace(/<[^>]*>/g,' ');if(/\.html">/.test(text))errors.push(`${rel}: exposed malformed anchor text`); for(const m of h.matchAll(/(?:href|src)="(\/[^"]+)"/g)){let p=m[1].split('#')[0].split('?')[0];if(!p||p.startsWith('//'))continue;let local=join(root,p.slice(1));if(p.endsWith('/'))local=join(local,'index.html');if(!existsSync(local))errors.push(`${rel}: broken local reference ${p}`)} publicUrls.push(urlFor(f));}
const sitemap=readFileSync(join(root,'sitemap.xml'),'utf8');const sitemapUrls=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]);for(const u of publicUrls)if(!sitemapUrls.includes(u))errors.push(`sitemap missing ${u}`);for(const u of sitemapUrls)if(!publicUrls.includes(u))errors.push(`sitemap extra ${u}`);
console.log(`QA scanned ${files.length} indexable public pages.`);if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('PASS: metadata, canonical, GA4, IDs, local file refs, and sitemap consistency.');
